### ISSUE TITLE
modify modern_cmake folder structure, adapt to cocos2d-x-external

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-external#2]
modern_cmake Repo: https://github.com/crazyhappygame/modern_cmake

- keep root folder __tools__ as origin
- rename root folder: __engine__ into __source__ ,make it more clear
- new root folder: __tests__ , move game1, game2 both test projects into __tests__ 

__source/external__ is the 3rd-party source libraries location.

**Comment by crazyhappygame** [comment]
I propose to remove source/external and have
source/Box2D
source/recast

and move source/engine to tests folder

**Comment by crazyhappygame** [comment]
And maybe also rename source to src ( windows does not like long paths ... )

**Comment by drelaptop** [comment]
`source/external` is clear, rename `source` to src is better than make `source/Box2D`. 

do it later.
