### ISSUE TITLE
make Travis & Appveyor task works

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-external#3]
## travis

7/8 travis task pass, 1/8 failed. should fix it

see the travis log

https://travis-ci.org/cocos2d/cocos2d-x-external

## appveyor

I can't login appveyor, such errors occur when try to login

```
There was an error while creating new AppVeyor account. Please contact AppVeyor support.
```

**Comment by crazyhappygame** [comment]
To fix travis error in https://github.com/cocos2d/cocos2d-x-external/blob/master/tests/game1/android/app/build.gradle and https://github.com/cocos2d/cocos2d-x-external/blob/master/tests/game2/android/app/build.gradle
change:
`path "../../../CMakeLists.txt"`
to
`path "../../../../CMakeLists.txt"`

**Comment by drelaptop** [comment]
Travis works

**Comment by drelaptop** [comment]
Appveyor CI works, could you paste here the build status link address in you free time?  @minggo  just like travis build status ![Build status](https://travis-ci.org/cocos2d/cocos2d-x-external.svg?branch=master)

I want to add it into README, but I can't access to the appveyor manage page.

**Comment by minggo** [comment]
I think you have the permission to do it, you are in `Collaborators`.

**Comment by crazyhappygame** [comment]
Please enable "appveyor rolling builds"

**Comment by drelaptop** [comment]
I can't login appveyor with my github account, I always get this error:

![image](https://user-images.githubusercontent.com/26329291/43496796-cc09cb04-9571-11e8-943e-19cbc5ad7f73.png)

**Comment by minggo** [comment]
@crazyhappygame i enabled it.

**Comment by crazyhappygame** [comment]
@minggo To close this task we need appveyor "build status link address"

**Comment by minggo** [comment]
It seems `appveyor` is added with my github account. So the status link address is `https://ci.appveyor.com/project/minggo/cocos2d-x-external/branch/master`.

**Comment by crazyhappygame** [comment]
@minggo what we news is link to status badge:
https://www.appveyor.com/docs/status-badges/

**Comment by drelaptop** [comment]
@crazyhappygame I got it, we can use this policy to get badge

> Badges for projects with public repositories on GitHub and Bitbucket
You can infer badge URL for projects with public repositories, well, provided there is only a single project with this repository in AppVeyor.

https://ci.appveyor.com/api/projects/status/github/cocos2d/cocos2d-x-external?branch=master&svg=true

![](https://ci.appveyor.com/api/projects/status/github/cocos2d/cocos2d-x-external?branch=master&svg=true)

the specific string like `32r7s2skrgm9ubva` in the address isn't necessary, great!

**Comment by minggo** [comment]
I updated the README.
