### ISSUE TITLE
Copy 3rd-party-libs source code

### ISSUE THREAD

**Issue by crazyhappygame** [cocos2d/cocos2d-x-external#4]
@drelaptop Could you copy current cocos2dx-3.17 3rd-party libs source code from:
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin
and
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src
to: 
https://github.com/cocos2d/cocos2d-x-external/source/external
?

It would be good to in cocos2d-x-external the same code which is in currently in cocos2dx-3.17.

If there are different patches for different platform we should fix it (probably just copy without patch and than add ifdef ). We have to have exactly the same code for all platforms.

**Comment by drelaptop** [comment]
copy android-specific from 3rd-party-libs-bin https://github.com/cocos2d/cocos2d-x-external/pull/6
