### ISSUE TITLE
Use GLOB, GLOB_RECURSE ?

### ISSUE THREAD

**Issue by crazyhappygame** [cocos2d/cocos2d-x-external#7]
I propose to use GLOB and GLOB_RECURSE (+1 for GLOB from me :) )

I do not have here strong position but let's discuss if we will use GLOB or not.

There is only one problem with glob when "source is added or removed". 

https://cmake.org/cmake/help/v3.12/command/file.html#glob
`Note We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate. The CONFIGURE_DEPENDS flag may not work reliably on all generators, or if a new generator is added in the future that cannot support it, projects using it will be stuck. Even if CONFIGURE_DEPENDS works reliably, there is still a cost to perform the check on every rebuild.`

But  CMakeLists.txt is much, much simpler with GLOB-ing

```
file(GLOB helloworld_SRC
    "*.h"
    "*.cpp"
)
add_executable(helloworld ${helloworld_SRC})
```

We will not "add or remove" external sources during game development...

I propose also add includes ("*.h") with GLOB. In that way you will see it XCode, VS.

**Comment by drelaptop** [comment]
maybe we can select to use GLOB and GLOB_RECURSE at `external` libs, but not `cocos2d-x` specific code. 

what's your option ? @v1993 , I invite you for I know you use cmake to build cocos2d-x
